config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get :add, to: "home#add"
  resources :points
  get :get_csv, to: "home#get_csv"
  get :heatmap, to: "home#heatmap"
  get :ordinary, to: "home#ordinary"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/point.rb
class Point < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :points
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @point = Point.new
    @points = Point.where.not(lat: [nil, 0.0], lon: [nil, 0.0], decibel: nil).order(:id)
  end

  def ordinary
    @point = Point.new
    @points = Point.where(by_hand: false).where.not(lat: [nil, 0.0], lon: [nil, 0.0], decibel: nil).order(:id)
  end

  def add
    @point = Point.new
  end

  def get_csv
    csv = to_csv(Point.all.order(id: :desc))
    send_data csv, :type => 'text/csv; charset=utf-8; header=present', :disposition => "attachment; filename=#{Date.today}.csv"
  end

  def heatmap
    @points = Point.where.not(lat: [nil, 0.0], lon: [nil, 0.0], decibel: nil)
  end

  private
  require 'csv'
  def to_csv(collection)
    attributes = collection.first.attribute_names
    CSV.generate(headers: true) do |csv|
      csv << attributes
      collection.each do |instance|
        csv << attributes.map{ |attr| instance.send(attr) }
      end
    end
  end
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  before_action :set_point, only: [:edit, :update, :destroy]
  def index
    @q =  Point.ransack(params[:q])
    @points = @q.result.page(params[:page]).per(50)
  end

  def create
    current_user.points.create(point_params)
    redirect_to root_path
  end

  def edit

  end

  def update
    #redirect_back(fallback_location: root_path) unless @point.user == current_user
    @point.update(point_params)
    redirect_to points_path
  end

  def destroy
    redirect_to points_path unless @point.user == current_user
    @point.destroy
    redirect_to points_path
  end

  private

  def set_point
    @point = Point.find(params[:id])
  end

  def point_params
    params.require(:point).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def get_color(point)
    case point.decibel
    when 0..50
      '#31fc03'
    when 51..70
      '#fce803'
    when 70..999
      '#fc0320'
    else
      '#030303'
    end
  end
end

app/helpers/points_helper.rb
module PointsHelper
end

app/views/home/1index.html.erb
<div id="map"></div>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBm2rSuphVK9QJyiyPkd4LN1SQj7yeMnw0&region=RU&&libraries=places"></script>
<style>
    #map {
        height: 800px;
        width: 100%;
    }
</style>
<script>

    var pos;
    var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 18,
    });

    function getLocation() {
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(showPosition);
        } else {
            alert("Geolocation is not supported by this browser.");
        }
    }
    function showPosition(position) {
        var lat = position.coords.latitude;
        var lng = position.coords.longitude;
        pos = new google.maps.LatLng(lat, lng)
        map.setCenter(pos);
        setMarker();
    }

    function setMarker() {
        marker = new google.maps.Marker(
            {
                map: map,
                draggable: true,
                animation: google.maps.Animation.DROP,
                position: pos
            });


        google.maps.event.addListener(marker, 'dragend', function () {
            geocodePosition(marker.getPosition());
        });
    }
    function geocodePosition(pos)
    {
        geocoder = new google.maps.Geocoder();
        geocoder.geocode
        ({
                latLng: pos
            },
            function(results, status)
            {
                if (status == google.maps.GeocoderStatus.OK)
                {
                    $("#mapSearchInput").val(results[0].formatted_address);
                    $("#mapErrorMsg").hide(100);
                }
                else
                {
                    $("#mapErrorMsg").html('Cannot determine address at this location.'+status).show(100);
                }
            }
        );
    }

    getLocation();
</script>

app/views/home/_main_map.html.erb
<div id="map"></div>
<div class="text-center">
  <button id="style" class="btn" style="background: #fcf003">Светлый стиль</button>
  <button id="add_pin" class="btn" style="background: #03fcf4">Добавить точку</button>
  <button class="btn" style="background: #31fc03"></button> - менее 50 дБ,
  <button class="btn" style="background: #fce803"></button> - 51-70 дБ,
  <button class="btn" style="background: #fc0320"></button> - более 70 дБ
</div>
<div class="text-center">
  <%= link_to 'Добавить точку', add_path, class: 'btn btn-success mt-3', style: 'border-radius: 18px; width: 80%' %>
  <%= link_to 'Все точки', points_path, class: 'btn btn-secondary mt-3', style: 'border-radius: 18px; width: 80%' %>
  <%= link_to 'Экспорт csv', get_csv_path, class: 'btn btn-secondary mt-3', style: 'border-radius: 18px; width: 80%' %>
</div>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBm2rSuphVK9QJyiyPkd4LN1SQj7yeMnw0&region=RU&&libraries=places"></script>
<style>
    #map {
        height: 600px;
        width: 100%;
    }
</style>
<script>

    var map, infoWindow;
    var pos;
    var marker;
    function initMap() {
        map = new google.maps.Map(document.getElementById("map"), {
            center: { lat: <%= @points.last.lat %>, lng: <%= @points.last.lon %> },
            zoom: 19,
            styles: [
                {
                    "featureType": "all",
                    "elementType": "all",
                    "stylers": [
                        {
                            "invert_lightness": true
                        },
                        {
                            "saturation": "-9"
                        },
                        {
                            "lightness": "0"
                        },
                        {
                            "visibility": "simplified"
                        }
                    ]
                },
                {
                    "featureType": "landscape.man_made",
                    "elementType": "all",
                    "stylers": [
                        {
                            "weight": "1.00"
                        }
                    ]
                },
                {
                    "featureType": "road.highway",
                    "elementType": "all",
                    "stylers": [
                        {
                            "weight": "0.49"
                        }
                    ]
                },
                {
                    "featureType": "road.highway",
                    "elementType": "labels",
                    "stylers": [
                        {
                            "visibility": "on"
                        },
                        {
                            "weight": "0.01"
                        },
                        {
                            "lightness": "-7"
                        },
                        {
                            "saturation": "-35"
                        }
                    ]
                },
                {
                    "featureType": "road.highway",
                    "elementType": "labels.text",
                    "stylers": [
                        {
                            "visibility": "on"
                        }
                    ]
                },
                {
                    "featureType": "road.highway",
                    "elementType": "labels.text.stroke",
                    "stylers": [
                        {
                            "visibility": "off"
                        }
                    ]
                },
                {
                    "featureType": "road.highway",
                    "elementType": "labels.icon",
                    "stylers": [
                        {
                            "visibility": "on"
                        }
                    ]
                }
            ]
        });
        setMarkers();


    }

    function handleLocationError(browserHasGeolocation, infoWindow, pos) {
        infoWindow.setPosition(pos);
        infoWindow.setContent(
            browserHasGeolocation
                ? "Error: The Geolocation service failed."
                : "Error: Your browser doesn't support geolocation."
        );
        infoWindow.open(map);
    }

    initMap();

    function setMarkers() {
        var infowindow = new google.maps.InfoWindow({
            size: new google.maps.Size(150, 50)
        });
        <% @points.each do |point| %>
        marker<%= point.id %> = new google.maps.Marker(
            {
                map: map,
                position: {lat: <%= point.lat %>, lng: <%= point.lon %>},
                label: '<%= point.decibel.round %>',
                icon: {
                    path: google.maps.SymbolPath.CIRCLE,
                    fillColor: '<%= get_color(point) %>',
                    fillOpacity: 0.6,
                    strokeColor: '#000',
                    strokeWeight: 1,
                    scale: 16,
                }
            });
        marker<%= point.id %>.addListener('click', function(event) {
            infowindow.setContent("<h4><%= point.decibel %> дБ</h3> <a class='btn btn-secondary' href='<%= edit_point_path(point) %>' target='_blank'>Ред</a>");
            infowindow.setPosition(event.latLng);
            infowindow.open(map);
        });
        <% end %>

    }

    $("#add_pin").click(function() {
        var new_marker = new google.maps.Marker({
            position: {lat: map.getCenter().lat(), lng: map.getCenter().lng()},
            map: map,
            draggable: true
        });
        var infowindow = new google.maps.InfoWindow({
            size: new google.maps.Size(250, 150)
        });
        new_marker.addListener('click', function(event) {
            infowindow.setContent("<form action='/points' method='post'><input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'> <input class='form-control' placeholder='Среднее значение (дБ)' type='text' name='point[decibel]' id='point_decibel'> <input id='form_lat' type='hidden' name='point[lat]' value='" +
                event.latLng.lat()
                + "'> <input id='form_lon' type='hidden' name='point[lon]' value='" +
                event.latLng.lng()
                + "'> <br /> <input type='submit' name='commit' value='Сохранить' class='btn btn-success' data-disable-with='Сохранить'></form>");
            infowindow.setPosition(event.latLng);
            infowindow.open(map);
        });
    });

    $("#style").click(function() {
        if (map.styles[0]['stylers'][0].invert_lightness) {
            map.setOptions({styles: [
                    {
                        "featureType": "all",
                        "elementType": "all",
                        "stylers": [
                            {
                                "invert_lightness": false
                            },
                            {
                                "saturation": "-9"
                            },
                            {
                                "lightness": "0"
                            },
                            {
                                "visibility": "simplified"
                            }
                        ]
                    },
                    {
                        "featureType": "landscape.man_made",
                        "elementType": "all",
                        "stylers": [
                            {
                                "weight": "1.00"
                            }
                        ]
                    },
                    {
                        "featureType": "road.highway",
                        "elementType": "all",
                        "stylers": [
                            {
                                "weight": "0.49"
                            }
                        ]
                    },
                    {
                        "featureType": "road.highway",
                        "elementType": "labels",
                        "stylers": [
                            {
                                "visibility": "on"
                            },
                            {
                                "weight": "0.01"
                            },
                            {
                                "lightness": "-7"
                            },
                            {
                                "saturation": "-35"
                            }
                        ]
                    },
                    {
                        "featureType": "road.highway",
                        "elementType": "labels.text",
                        "stylers": [
                            {
                                "visibility": "on"
                            }
                        ]
                    },
                    {
                        "featureType": "road.highway",
                        "elementType": "labels.text.stroke",
                        "stylers": [
                            {
                                "visibility": "off"
                            }
                        ]
                    },
                    {
                        "featureType": "road.highway",
                        "elementType": "labels.icon",
                        "stylers": [
                            {
                                "visibility": "on"
                            }
                        ]
                    }
                ]});
        }
    });


</script>

app/views/home/add.html.erb
<h3 class="text-center ">Добавить точку</h3>
<div class="container-lg">
  <div id="map"></div>
  <p>Координаты точки: <div id=coords></div></p>
  <%= form_for @point do |f| %>
    <%= render 'points/form', f: f %>
  <% end %>
</div>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBm2rSuphVK9QJyiyPkd4LN1SQj7yeMnw0&region=RU&&libraries=places"></script>
<style>
    #map {
        height: 400px;
        width: 100%;
    }
</style>
<script>

    let map, infoWindow;
    var pos;
    var marker;
    function initMap() {
        map = new google.maps.Map(document.getElementById("map"), {
            center: { lat: -34.397, lng: 150.644 },
            zoom: 19,
        });
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(
                    (position) => {
                        pos = {
                            lat: position.coords.latitude,
                            lng: position.coords.longitude,
                        };
                        map.setCenter(pos);
                        pos = new google.maps.LatLng(pos.lat, pos.lng);
                        setMarker();
                        updateFields();
                    },
                    () => {
                        handleLocationError(true, infoWindow, map.getCenter());
                    }
                );
            } else {
                // Browser doesn't support Geolocation
                handleLocationError(false, infoWindow, map.getCenter());
            }

    }

    function handleLocationError(browserHasGeolocation, infoWindow, pos) {
        infoWindow.setPosition(pos);
        infoWindow.setContent(
            browserHasGeolocation
                ? "Error: The Geolocation service failed."
                : "Error: Your browser doesn't support geolocation."
        );
        infoWindow.open(map);
    }

    initMap();

    function setMarker() {
        marker = new google.maps.Marker(
            {
                map: map,
                draggable: true,
                animation: google.maps.Animation.DROP,
                position: pos
            });

        google.maps.event.addListener(marker, 'dragend', function () {
            updateFields();
        });
    }
    function updateFields() {
        $('#coords').html(marker.getPosition().lat() + ', ' + marker.getPosition().lng())
        $('#form_lat').val(marker.getPosition().lat())
        $('#form_lon').val(marker.getPosition().lng())
    }


</script>

app/views/home/index.html.erb
<div id="map"></div>
<div class="text-center">
  <button id="add_pin" class="btn" style="background: #03fcf4">Добавить точку</button>
  <button class="btn" style="background: #31fc03"></button> - 30-60 дБ,
  <button class="btn" style="background: #fce803"></button> - 61-90 дБ,
  <button class="btn" style="background: #fc0320"></button> - более 90 дБ
</div>
<div class="text-center">
  <%= link_to 'Добавить точку', add_path, class: 'btn btn-success mt-3', style: 'border-radius: 18px; width: 80%' %>
  <%= link_to 'Все точки', points_path, class: 'btn btn-secondary mt-3', style: 'border-radius: 18px; width: 80%' %>
  <%= link_to 'Экспорт csv', get_csv_path, class: 'btn btn-secondary mt-3', style: 'border-radius: 18px; width: 80%' %>
</div>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBm2rSuphVK9QJyiyPkd4LN1SQj7yeMnw0&region=RU&&libraries=places"></script>
<style>
    #map {
        height: 600px;
        width: 100%;
    }
</style>
<script>

    var map, infoWindow;
    var pos;
    var marker;
    function initMap() {
        map = new google.maps.Map(document.getElementById("map"), {
            center: { lat: <%= @points.last.lat %>, lng: <%= @points.last.lon %> },
            zoom: 19,
            styles: [
                {
                    "featureType": "all",
                    "elementType": "all",
                    "stylers": [
                        {
                            "invert_lightness": true
                        },
                        {
                            "saturation": "-9"
                        },
                        {
                            "lightness": "0"
                        },
                        {
                            "visibility": "simplified"
                        }
                    ]
                },
                {
                    "featureType": "landscape.man_made",
                    "elementType": "all",
                    "stylers": [
                        {
                            "weight": "1.00"
                        }
                    ]
                },
                {
                    "featureType": "road.highway",
                    "elementType": "all",
                    "stylers": [
                        {
                            "weight": "0.49"
                        }
                    ]
                },
                {
                    "featureType": "road.highway",
                    "elementType": "labels",
                    "stylers": [
                        {
                            "visibility": "on"
                        },
                        {
                            "weight": "0.01"
                        },
                        {
                            "lightness": "-7"
                        },
                        {
                            "saturation": "-35"
                        }
                    ]
                },
                {
                    "featureType": "road.highway",
                    "elementType": "labels.text",
                    "stylers": [
                        {
                            "visibility": "on"
                        }
                    ]
                },
                {
                    "featureType": "road.highway",
                    "elementType": "labels.text.stroke",
                    "stylers": [
                        {
                            "visibility": "off"
                        }
                    ]
                },
                {
                    "featureType": "road.highway",
                    "elementType": "labels.icon",
                    "stylers": [
                        {
                            "visibility": "on"
                        }
                    ]
                }
            ]
        });
        setMarkers();


    }

    function handleLocationError(browserHasGeolocation, infoWindow, pos) {
        infoWindow.setPosition(pos);
        infoWindow.setContent(
            browserHasGeolocation
                ? "Error: The Geolocation service failed."
                : "Error: Your browser doesn't support geolocation."
        );
        infoWindow.open(map);
    }

    initMap();

    function setMarkers() {
        var infowindow = new google.maps.InfoWindow({
            size: new google.maps.Size(150, 50)
        });
        <% @points.each do |point| %>
          marker<%= point.id %> = new google.maps.Marker(
              {
                  map: map,
                  position: {lat: <%= point.lat %>, lng: <%= point.lon %>},
                  label: '<%= point.decibel.round %>',
                  icon: {
                      path: google.maps.SymbolPath.CIRCLE,
                      fillColor: '<%= get_color(point) %>',
                      fillOpacity: 0.6,
                      strokeColor: '#000',
                      strokeWeight: 1,
                      scale: 16,
                  }
              });
        marker<%= point.id %>.addListener('click', function(event) {
            infowindow.setContent("<h4><%= point.decibel %> дБ</h3> <a class='btn btn-secondary' href='<%= edit_point_path(point) %>' target='_blank'>Ред</a>");
            infowindow.setPosition(event.latLng);
            infowindow.open(map);
        });
        <% end %>

    }

  $("#add_pin").click(function() {
      var new_marker = new google.maps.Marker({
          position: {lat: map.getCenter().lat(), lng: map.getCenter().lng()},
          map: map,
          draggable: true
      });
      var infowindow = new google.maps.InfoWindow({
          size: new google.maps.Size(250, 150)
      });
      new_marker.addListener('click', function(event) {
          infowindow.setContent("<form action='/points' method='post'><input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'> <input class='form-control' placeholder='Среднее значение (дБ)' type='text' name='point[decibel]' id='point_decibel'> <input id='form_lat' type='hidden' name='point[lat]' value='" +
              map.getCenter().lat()
              + "'> <input id='form_lon' type='hidden' name='point[lon]' value='" +
              map.getCenter().lng()
              + "'> <input type='submit' name='commit' value='Сохранить' class='btn btn-success' data-disable-with='Сохранить'></form>");
          infowindow.setPosition(event.latLng);
          infowindow.open(map);
      });
  });


</script>

app/views/home/ordinary.html.erb
<%= render 'main_map' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <title>Acoustic in the City</title>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to 'Acoustic in the City', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to 'Добавить точку', add_path, class: 'nav-link' %>
        </li>
        <li class="nav-item active">
          <%= link_to 'Все точки', points_path, class: 'nav-link' %>
        </li>
        <li class="nav-item active">
          <%= link_to 'Экспорт csv', get_csv_path, class: 'nav-link' %>
        </li>
        <li class="nav-item active">
          <%= link_to 'Heatmap', heatmap_path(radius: 0.005), class: 'nav-link' %>
        </li>
        <li class="nav-item active">
          <%= link_to 'Обычные точки', ordinary_path, class: 'nav-link' %>
        </li>
        <% if current_user %>
          <li class="nav-item active">
            <%= link_to 'Профиль', edit_registration_path(current_user), class: 'nav-link' %>
          </li>
          <li class="nav-item active">
            <%= link_to 'Выход', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/points/_form.html.erb
<h5 >Введите показания</h5>
<div class="form-group">
  <%= f.text_field :decibel, class: 'form-control', placeholder: 'Среднее значение (дБ)' %>
</div>
<div class="form-group">
  <%= f.text_field :frequency, class: 'form-control', placeholder: 'Частота' %>
</div>
<div class="form-group">
  <%= f.text_field :minutes, class: 'form-control', placeholder: 'Продолжительность измерений (мин)' %>
</div>
<div class="form-group">
  <%= f.text_field :comment, class: 'form-control', placeholder: 'Комментарий' %>
</div>
<div class="form-group">
  <%= f.check_box :wind %>
  <%= f.label :wind, 'во время измерения был сильный ветер' %>
</div>
<div class="form-group">
  <%= f.check_box :park %>
  <%= f.label :park, 'измерение проведено в парке' %>
</div>
<div class="form-group">
  <%= f.check_box :shosse %>
  <%= f.label :shosse, 'измерение проведено рядом с трассой' %>
</div>
<div class="form-group">
  <%= f.check_box :road %>
  <%= f.label :road, 'измерение проведено рядом с дорогой' %>
</div>
<div class="form-group">
  <%= f.check_box :yard %>
  <%= f.label :yard, 'измерение проведено во дворе' %>
</div>
<div class="form-group">
  <%= f.check_box :building %>
  <%= f.label :building, 'измерение проведено в помещении' %>
</div>
<div class="form-group">
  <%= f.check_box :by_hand %>
  <%= f.label :by_hand, 'это ручной ввод' %>
</div>
<%= f.hidden_field :lat, id: 'form_lat' %>
<%= f.hidden_field :lon, id: 'form_lon' %>
<div class="text-center">
  <%= f.submit 'Сохранить', class: 'btn btn-success', style: 'border-radius: 18px; width: 80%' %>
</div>

app/views/points/edit.html.erb
<h3 class="text-center ">Изменить точку</h3>
<div class="container-lg">
  <div id="map"></div>
  <p>Координаты точки: <div id=coords></div></p>
  <%= form_for @point do |f| %>
    <%= render 'form', f: f %>
  <% end %>
</div>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBm2rSuphVK9QJyiyPkd4LN1SQj7yeMnw0&region=RU&&libraries=places"></script>
<style>
    #map {
        height: 400px;
        width: 100%;
    }
</style>
<%
  if @point.lat.present? && @point.lon.present?
    lat = @point.lat
    lon = @point.lon
  else
    lat = 59.929395199999995
    lon = 30.346444799999993
  end
%>
<script>

    let map, infoWindow;
    var pos;
    var marker;
    function initMap() {
        map = new google.maps.Map(document.getElementById("map"), {

            center: { lat: <%= lat %>, lng: <%= lon %> },
            zoom: 19
        });
        setMarker();
    }

    initMap();

    function setMarker() {
        marker = new google.maps.Marker(
            {
                map: map,
                draggable: true,
                animation: google.maps.Animation.DROP,
                position: { lat: <%= lat %>, lng: <%= lon %> }
            });

        google.maps.event.addListener(marker, 'dragend', function () {
            updateFields();
        });
    }
    function updateFields() {
        $('#coords').html(marker.getPosition().lat() + ', ' + marker.getPosition().lng())
        $('#form_lat').val(marker.getPosition().lat())
        $('#form_lon').val(marker.getPosition().lng())
    }


</script>

app/views/points/index.html.erb
<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
  <thead>
  <tr>
    <th scope="col"><%= sort_link(@q, :id) %></th>
    <th scope="col">Автор</th>
    <th scope="col">Громкость</th>
    <th scope="col">Частота</th>
    <th scope="col">Продолжительность измерений</th>
    <th scope="col">Комментарий</th>
    <th scope="col">Координаты</th>
    <th scope="col">Дата</th>
    <th scope="col">Ред.</th>
    <th scope="col">Удалить</th>
  </tr>
  </thead>
  <tbody>
  <% @points.each do |point| %>
    <tr>
      <td><%= point.id %></td>
      <td><%= point.user&.name %></td>
      <td><%= point.decibel %></td>
      <td><%= point.frequency %></td>
      <td><%= point.minutes %></td>
      <td><%= point.comment %></td>
      <td><%= point.lat.round(5) if point.lat %>, <%= point.lon.round(5) if point.lon %></td>
      <td><%= point.created_at.in_time_zone("Moscow").strftime("%Y-%m-%d %k:%M") %></td>
      <td><%= link_to '>', edit_point_path(point), class: 'btn btn-secondary' %></td>
      <td><%= link_to '-', point_path(point), method: :delete, class: 'btn btn-danger' if point.user == current_user %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= paginate @points, theme: 'twitter-bootstrap-4' %>